import { Search, SearchUsers, SearchRepo } from './Search';
import DropDown from './DropDown';
import Issues from './Issues';
import IssueBoard from './IssueBoard';
import User from './User';
import Pagination from './Pagination';
import Info from './Info';
import Loader from './Loader';
import Views from './Views';
export { Search, DropDown, Issues, IssueBoard, User, SearchUsers, SearchRepo, Pagination, Loader, Info, Views };
